export default [{ rules: {
  'arrow-body-style': 'warn',
  'arrow-spacing': 'warn',
  'block-spacing': ['warn', 'always'],
  'brace-style': ['warn', '1tbs', { 'allowSingleLine': true }],
  'comma-dangle': ['warn', 'always-multiline'],
  'comma-spacing': 'warn',
  'eol-last': ['warn', 'never'],
  'func-call-spacing': 'warn',
  'indent': ['warn', 2, { 'ignoredNodes': ['PropertyDefinition'], 'SwitchCase': 1 }],
  'keyword-spacing': 'warn',
  'multiline-comment-style': 'warn',
  'no-multi-spaces': 'warn',
  'object-curly-spacing': ['warn', 'always', { objectsInObjects: false }],
  'quotes': ['warn', 'single', { allowTemplateLiterals: true, avoidEscape: true }],
  'semi': ['warn', 'never'],
  'space-before-blocks': 'warn',
  'template-curly-spacing': ['warn', 'never'],
}}]